---
# tasks file for provision/roles/hardening_debian
- name: system upgrade 
  include: updatedpack.yml
- name: harden ssh 
  include: sshd.yml
- name: configuring firewall 
  include: firewall.yml
- name: configuring bruteforce protection
  include: bruteforce.yml
- name: securing kernel params
  include: kernel.yml
